"""initial migration

Revision ID: d28d97ab4ad1
Revises: 
Create Date: 2025-12-13 00:13:53.358204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28d97ab4ad1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_id'), 'missions', ['id'], unique=False)
    op.create_index(op.f('ix_missions_title'), 'missions', ['title'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('gear', sa.JSON(), nullable=True),
    sa.Column('transport', sa.String(), nullable=True),
    sa.Column('critique_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_versions_id'), 'plan_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_versions_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_missions_title'), table_name='missions')
    op.drop_index(op.f('ix_missions_id'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
